---
#
# Build a podman container and push it to quay.io
#
name: build_image

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # This process described by Hitesh Jethva, June 12, 2021
    # https://www.atlantic.net/dedicated-server-hosting/how-to-install-and-use-podman-on-ubuntu-20-04/
    - name: Add containers repo to apt sources
      run: |
        source /etc/os-release
        sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
        wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | sudo apt-key add -
        sudo apt-get update -qq -y
        
    - name: Install podman
      run: |
        sudo apt-get -qq --yes install podman
        podman --version

    - name: Install buildah
      run: |
        sudo apt-get -qq --yes install buildah

    - name: Checkout the current repository
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    
    - name: Build the package
      run: |
        make build


    - name: Tag the image
      run: |
        podman tag miniboot quay.io/markllama/miniboot


    - name: Log into quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
